#配置服务器信息
server:
  port: 8003
  #context-path: /study 配置根目录


#数据库信息配置
spring:
  application:
    name: study-springcloud-dept  #对外暴露应用名称(在eureka里的应用服务名字)
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb03?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #druid连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters,去掉监控界面sql无法统计，‘wall’用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    userGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml               # mybatis配置文件所在路径
  type-aliases-package: com.andlinks.springcloud.pojo.entity     # 所有Entity别名类所在包
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    cache-enabled: true #开启二级缓存

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7222.com:7222/eureka,http://eureka7333.com:7333/eureka
  instance:
    instance-id: microservicecloud-dept8003  #自定义服务名称信息
    prefer-ip-address: true  # 访问路径可以显示ip


mysql:
  location: /Users/yalan/.m2/repository/mysql/mysql-connector-java/5.1.47/mysql-connector-java-5.1.47.jar


info:
  app.name: service-cloud
  companyName: andlinks
  build.artifactId: springcloud-study-provider-dept-8003
  build.version: 1.0-SNAPSHOT